language: scala

# Because exasol/docker-db requires privileged mode
sudo: required
dist: trusty
services: docker

scala:
  - 2.11.12

addons:
  apt:
    packages:
      - shellcheck

jdk:
  - openjdk8
  - oraclejdk8

before_install:
  - docker pull exasol/docker-db:latest
  - docker network create -d bridge --subnet 192.168.0.0/24 --gateway 192.168.0.1 dockernet

script:
  - travis_wait 30 ./scripts/ci.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.sbt/1.0
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/cache
  - $HOME/.sbt/launchers
  - $HOME/.ivy2
  - $HOME/.coursier

before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - du -h -d 4 $HOME/.coursier/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.coursier/cache -name "*.lock" -type f -delete
